version: '3.8'

services:
  iris-predictor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    volumes:
      # Mount the model file for development
      - ../iris_model.pkl:/app/iris_model.pkl
    restart: unless-stopped
